/* eslint-disable */
//file generated by create-react-app; polyfill must be imported before enzyme which violates eslint rules
// import './tempPolyfills';
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({
  adapter: new Adapter(),
});
